#!/bin/bash
#PBS -l select=1:ncpus=2:ngpus=1:mem=32gb
#PBS -l walltime=11:00:00
#PBS -M z5327748@ad.unsw.edu.au
#PBS -m abe
#PBS -j oe
#PBS -N CVoice13_ipav1_tonev2_5e04_withDiph
#PBS -o Output_5e04_ipav1_tonev2_withDiph.log


module load python/3.10
source /srv/scratch/z5327748/thesisB/bin/activate

cd /home/z5327748/Jinghao_thesis
python train.py --config_file=mandarin_katana_04.yaml train_SA_model
