#!/bin/bash
#PBS -l select=1:ncpus=2:ngpus=1:mem=32gb
#PBS -l walltime=7:00:00
#PBS -M z5327748@ad.unsw.edu.au
#PBS -m abe
#PBS -j oe
#PBS -N CVoice13_ipav2_tonev1_6e04_new
#PBS -o Output_5e04_ipav2_tonev1_new.log


module load python/3.10
source /srv/scratch/z5327748/thesisB/bin/activate

cd /home/z5327748/Jinghao_thesis
python train.py --config_file=configs/mandarin_katana_03.yaml train_SA_model --resume_from_checkpoint='/srv/scratch/z5327748/modelResult/ThesisA/cV13_ipav2_tonev1_new/fine_tune/checkpoint-16000'
